config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'

  resources :photos
  post 'photos/follow_user' => 'photos#follow_user'

  get "/auth/:provider/callback" => "sessions#create"
  get "/signout" => "sessions#destroy", :as => :signout

end

app/models/user.rb
class User < ActiveRecord::Base

  def self.create_with_omniauth(auth)
    create! do |user|
      user.provider = auth["provider"]
      user.uid = auth["uid"]
      user.name = auth["info"]["name"]
    end
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def hello
    render text: "hello, world!"
  end

  helper_method :current_user

  private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController

  def index
    client = Instagram.client(:access_token => session[:access_token])
    @photos = client.tag_recent_media('foodie')
  end

  def follow_user
    id = params[:id]
    Instagram.client(:access_token => session[:access_token]).follow_user(id)    

    respond_to do |format|
      format.json { render :json => {} }
    end
  end


end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def create
    auth = request.env["omniauth.auth"]
    user = User.find_by_provider_and_uid(auth["provider"], auth["uid"]) || User.create_with_omniauth(auth)
    session[:user_id] = user.id
    session[:access_token] = auth.credentials.token
    redirect_to root_url, :notice => "Signed in!"
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, :notice => "Signed out!"
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>InstaHelper</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %> 
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/photos/_photo.html.erb
<div class="card">
  <div class="content">
<!--     <div class="right floated meta"><%= time_ago_in_words(Time.at(photo.created_time.to_i)) %></div> -->
    <img class="ui avatar image" src= <%= photo.user.profile_picture %>> <%= photo.user.username %>
  </div>
  <div class="image">
    <%= image_tag photo.images.low_resolution.url %>
  </div>
  <div class="extra content">
    <div class="ui one buttons fluid follow-btn" data-id="<%= photo.user.id %>">
      <div class="ui basic green button">Follow</div>
    </div>
  </div>
</div>

app/views/photos/index.html.erb
<br><br>

<!-- <%= @photos.first.user %> -->

<div class="ui four stackable cards container">

  <% @photos.each do |photo| %>

    <%= render partial: "photo", object: photo %>

  <% end %>

</div>

app/views/static_pages/home.html.erb
<% if current_user %>
  Welcome <%= current_user.name %>!
  <%= link_to "Sign Out", signout_path %>
<% else %>
  <%= link_to "Sign in with Instagram", "/auth/instagram" %>
<% end %>

<br><br>
<%= link_to 'photos', photos_path %>